#!/usr/bin/expect 

if { [llength $argv] < 2} { 
    puts "Usage:" 
    puts "$argv0 <Image path> IP" 
    puts "$argv0 <Image path> IP <path>" 
    exit 1 
} 

set timeout 20 
set Local_File [lindex $argv 0] 
set IP [lindex $argv 1]
set STRING 0 
spawn ssh-keygen -f "/home_a/matao/.ssh/known_hosts" -R $IP

proc myscpfunc { STRING1 } {
    set passwd 0penBmc
    set passwderror 0 
    expect { 
        "*assword:*" { 
            if { $passwderror == 1 } { 
            puts "passwd is error" 
            exit 2 
            } 
            set timeout 1000 
            set passwderror 1 
            send "$passwd\r" 
            exp_continue 
        } 
        "yes/no" { 
            send "yes\r" 
            exp_continue 
        } 
        timeout { 
            puts "connect is timeout" 
            exit 3 
        } 
    } 
}


if { [llength $argv] == 2} { 
    if {[regexp -nocase "obmc-phosphor-image" $Local_File]} {
        spawn scp $Local_File root@$IP:/tmp/images
        myscpfunc $STRING

        spawn scp /home_a/matao/usr/local/bin/BMC_upgrade.sh root@$IP:~/
        myscpfunc $STRING
    } else {
        spawn scp $Local_File /home_a/matao/usr/local/bin/BMC_upgrade.sh root@$IP:~/
        myscpfunc $STRING
    }
    
} 

if { [llength $argv] == 3} { 
    set path [lindex $argv 2]
    spawn scp $Local_File  root@$IP:$path
    myscpfunc $STRING
} 
