#!/usr/bin/expect 
set timeout 20 
 
if { [llength $argv] < 2} { 
    puts "Usage:" 
    puts "$argv0 local_file IP" 
    exit 1 
} 
 
set local_file [lindex $argv 0] 
set IP [lindex $argv 1] 
set passwd 0penBmc
 
set passwderror 0 

spawn ssh-keygen -f "/home/morton/.ssh/known_hosts" -R $IP

spawn scp $local_file /usr/local/morton/bmc_upgrade_for_ALI.sh root@$IP:~
 
expect { 
    "*assword:*" { 
        if { $passwderror == 1 } { 
        puts "passwd is error" 
        exit 2 
        } 
        set timeout 1000 
        set passwderror 1 
        send "$passwd\r" 
        exp_continue 
    } 
    "*yes/no*" {
        send "yes\r" 
        exp_continue 
    } 
    timeout { 
        puts "connect is timeout" 
        exit 3 
    } 
} 
